### ISSUE TITLE
Issue moving to next lab 

### ISSUE THREAD

**Issue by rightbrainpapi** [learn-co-curriculum/method-arguments-lab#12]
I successfully completed my lab but I am having trouble moving on to the next lab.

**Comment by drakeltheryuujin** [comment]
Hi @darnell03,

This request sounds like an issue with the Learn platform.
[Raising issues on GitHub][raise] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
