### ISSUE TITLE
Having issues..

### ISSUE THREAD

**Issue by EMG114** [learn-co-curriculum/method-arguments-lab#6]
I am having issues pulling a request from this lesson...

**Comment by matbalez-zz** [comment]
what kind of issues are you having? 

is the problem isolated to this lesson specifically?

**Comment by EMG114** [comment]
I believe I am having some issues understanding the github and learn environment...I need to reread them. Thanks. Will come back if I can't resolve them....

**Comment by AnnJohn** [comment]
@EMG114 if you have questions about the topics and concepts discussed, please use the Ask a Question tool within Learn and one of our Learn Experts will be there to help you through any specific issues, questions, or problems. Thanks!
